#!/bin/bash

#When completed this file will create a system report
source /etc/os-release

echo " "
echo -e "System Report for $(hostname) generated by $USER,\non $(date +%c)\n"

echo -e "System information\n------------------------\n"
echo "OS: $PRETTY_NAME"
echo "Uptime: $(uptime -p)"
echo "CPU: $(lshw -c cpu 2>/dev/null | sed -n '/product/s/^.*product: //p')"
echo "RAM: $(lshw -c memory 2>/dev/null | sed -n '/size/s/^.*size: //p')"
echo "Disk(s): $(lsblk -d -n -o VENDOR,MODEL,SIZE | grep ATA)" 
echo "Graphics: $(lshw -c display 2>/dev/null | sed -n '/product/s/^.*product: //p')"
echo "Host Address:  $(ip a s enp0s3 | grep -w inet | awk '{print $2}')"
# Continue editing here
echo "Gateway Address: $(ip r | grep default | awk '{print $3}')"
echo "DNS Server: $(resolvectl status | grep -w Server | awk '{print $4}')"

echo -e "\nSysyem Status\n-----------------"
echo "Users Logged in:
$(who)"
echo "Disk Space:
$(df -h | awk '{printf "%-20s %-10s\n", $1,$4}')"
echo "Process Count: $(ps -e --no-headers | wc -l)"
echo "Load Averages: $(uptime | awk '{print $9,$10,$11}')"
echo "Listening Network Ports: $(ss -ltn | awk 'NR>1 {n=split($4, a, ":"); print a[n]}' | paste -sd ' ' -)"
echo "UFW Status: $(sudo ufw status)"
