#!/bin/bash

#When completed this file will create a system report
source /etc/os-release

echo " "
echo -e "System Report for $(hostname) generated by $USER,\non $(date +%c)\n"

echo -e "System information\n------------------------\n"
echo "OS: $PRETTY_NAME"
echo "Uptime: $(uptime -p)"
echo "CPU: $(lshw -c cpu 2>/dev/null | sed -n '/product/s/^.*product: //p')"
echo "RAM: $(lshw -c memory 2>/dev/null | sed -n '/size/s/^.*size: //p')"
echo "Disk(s): $(lsblk -d -n -o VENDOR,MODEL,SIZE | grep ATA)" 
echo "Graphics: $(lshw -c display 2>/dev/null | sed -n '/product/s/^.*product: //p')"
echo "Host Address:  $(ip a s enp0s3 | grep -w inet | awk '{print $2}')"
# Continue editing here
echo "Gateway Address: $(ip r)"
